### ISSUE TITLE
Official App?

### ISSUE THREAD

**Issue by naushad-madakiya** [PatilShreyas/GDG-Pune-DevFest-App#4]
Is this the official app or [this?](https://github.com/PatilShreyas/GDGPune-DevFest19-Android)

**Comment by PatilShreyas** [comment]
@naushad-madakiya This is now the official app. The link you mentioned here was a Kotlin project. It's migrated to Flutter now. This is part of @gdgpunegit now.

**Comment by naushad-madakiya** [comment]
Great! better if this can also be moved under the [organization](https://github.com/GDG-Pune)
